version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: docker_postgres
    environment:
      POSTGRES_USER: psqluser
      POSTGRES_PASSWORD: psqlpass
      POSTGRES_DB: bigdatatools1
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: